"""Build a conservative 54-figure evidence-gap audit.

This is a row-level engineering audit over the existing target registry and
validation table.  It does not invent claims or rewrite the canonical
validation rows; it only classifies each row as accepted, boundary, diagnostic,
or proxy and records missing artifact paths plus the existing next action.
"""

from __future__ import annotations

import csv
from collections import Counter
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
TARGETS = PROJECT_ROOT / "data" / "reproduction_targets.csv"
VALIDATION = PROJECT_ROOT / "data" / "computed" / "figure_validation_table.csv"
OUT_CSV = PROJECT_ROOT / "data" / "computed" / "figure_evidence_gap_audit.csv"
OUT_MD = PROJECT_ROOT / "docs" / "figure_evidence_gap_audit.md"

FIELDS = (
    "figure_id",
    "source_page",
    "acceptance_tier",
    "target_status",
    "script",
    "evidence_status",
    "current_repro_level",
    "uses_proxy",
    "script_exists",
    "png_exists",
    "pdf_exists",
    "missing_artifacts",
    "evidence_summary",
    "next_action",
)


def _read(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8-sig") as stream:
        return list(csv.DictReader(stream))


def _classify(row: dict[str, str]) -> str:
    proxy = row.get("uses_proxy", "").strip().lower()
    text = " ".join(
        row.get(field, "")
        for field in ("current_repro_level", "visual_status", "next_action", "key_physical_quantities")
    ).lower()
    if proxy == "true":
        return "proxy"
    if proxy == "partial":
        return "diagnostic"
    boundary_markers = (
        "boundary",
        "pending",
        "baseline",
        "source-layer",
        "source layer",
        "comparison",
        "overlay",
        "not a fully",
        "not yet",
        "high-fidelity",
    )
    if any(marker in text for marker in boundary_markers):
        return "boundary"
    return "accepted"


def _path_tokens(value: str) -> list[str]:
    tokens: list[str] = []
    for raw in value.split(";"):
        token = raw.strip().strip("` ")
        token = token.rstrip(".,")
        if token.startswith(("data/", "docs/", "outputs/", "figures/", "scripts/", "src/")):
            tokens.append(token)
    return tokens


def _artifact_status(row: dict[str, str]) -> tuple[str, str, str, list[str]]:
    script = row.get("script", "").replace("\\", "/")
    script_path = PROJECT_ROOT / Path(script) if script else None
    script_exists = bool(script_path and script_path.exists())
    suffix = row["figure_id"].replace(".", "_")
    png_path = PROJECT_ROOT / "outputs" / "figures_png" / f"fig_{suffix}.png"
    pdf_path = PROJECT_ROOT / "outputs" / "figures_pdf" / f"fig_{suffix}.pdf"
    png_exists = png_path.exists()
    pdf_exists = pdf_path.exists()
    missing: list[str] = []
    if not script_exists:
        missing.append(script or "script")
    for token in _path_tokens(row.get("main_data_source", "")):
        path = PROJECT_ROOT / Path(token)
        exists = any(PROJECT_ROOT.glob(token)) if any(mark in token for mark in "*?[") else path.exists()
        if not exists:
            missing.append(token)
    if not png_exists:
        missing.append(str(png_path.relative_to(PROJECT_ROOT)).replace("\\", "/"))
    if not pdf_exists:
        missing.append(str(pdf_path.relative_to(PROJECT_ROOT)).replace("\\", "/"))
    return str(script_exists).lower(), str(png_exists).lower(), str(pdf_exists).lower(), missing


def _write_csv(rows: list[dict[str, str]]) -> None:
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_CSV.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=FIELDS)
        writer.writeheader()
        writer.writerows({field: row.get(field, "") for field in FIELDS} for row in rows)


def _write_md(rows: list[dict[str, str]]) -> None:
    counts = Counter(row["evidence_status"] for row in rows)
    missing = [row for row in rows if row["missing_artifacts"]]
    lines = [
        "# 54-figure evidence-gap audit",
        "",
        "Generated by `scripts/run_figure_evidence_gap_audit.py` from",
        "`data/reproduction_targets.csv` and `data/computed/figure_validation_table.csv`.",
        "This report records existing evidence and bounded gaps; it does not rewrite",
        "the canonical validation table or add new scientific claims.",
        "",
        f"- Target rows: `{len(rows)}`",
        f"- Evidence status counts: `{dict(sorted(counts.items()))}`",
        f"- Rows with missing script/data/rendered artifact paths: `{len(missing)}`",
        "- Classification rule: `uses_proxy=true` -> proxy; `partial` -> diagnostic;",
        "  boundary/pending/baseline/source-layer/comparison language -> boundary;",
        "  otherwise -> accepted.",
        "",
    ]
    for status in ("accepted", "boundary", "diagnostic", "proxy"):
        group = [row for row in rows if row["evidence_status"] == status]
        lines.extend(
            [
                f"## {status}",
                "",
                "| figure | level | artifacts | evidence / gap | next action |",
                "|---|---|---|---|---|",
            ]
        )
        for row in group:
            artifacts = (
                f"script={row['script_exists']}, png={row['png_exists']}, pdf={row['pdf_exists']}"
                + (f"; missing: {row['missing_artifacts']}" if row["missing_artifacts"] else "")
            )
            lines.append(
                "| {figure_id} | {current_repro_level} | {artifacts} | {evidence_summary} | {next_action} |".format(
                    figure_id=row["figure_id"],
                    current_repro_level=row["current_repro_level"].replace("|", r"\|"),
                    artifacts=artifacts.replace("|", r"\|"),
                    evidence_summary=row["evidence_summary"].replace("|", r"\|"),
                    next_action=row["next_action"].replace("|", r"\|"),
                )
            )
        lines.append("")
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    targets = {row["figure_id"]: row for row in _read(TARGETS)}
    validation = _read(VALIDATION)
    if set(targets) != {row["figure_id"] for row in validation} or len(validation) != 54:
        raise SystemExit("target and validation tables must contain the same 54 figure ids")
    rows: list[dict[str, str]] = []
    for source in validation:
        target = targets[source["figure_id"]]
        script_exists, png_exists, pdf_exists, missing = _artifact_status(source)
        status = _classify(source)
        evidence_summary = source.get("visual_status", "")
        if missing:
            evidence_summary += f" Missing artifact paths: {', '.join(missing)}."
        rows.append(
            {
                "figure_id": source["figure_id"],
                "source_page": source.get("source_page", target.get("source_page", "")),
                "acceptance_tier": target.get("acceptance_tier", ""),
                "target_status": target.get("target_status", ""),
                "script": source.get("script", ""),
                "evidence_status": status,
                "current_repro_level": source.get("current_repro_level", ""),
                "uses_proxy": source.get("uses_proxy", ""),
                "script_exists": script_exists,
                "png_exists": png_exists,
                "pdf_exists": pdf_exists,
                "missing_artifacts": ";".join(missing),
                "evidence_summary": evidence_summary,
                "next_action": source.get("next_action", ""),
            }
        )
    _write_csv(rows)
    _write_md(rows)
    print(f"wrote {OUT_CSV.relative_to(PROJECT_ROOT)}")
    print(f"wrote {OUT_MD.relative_to(PROJECT_ROOT)}")
    print(f"status_counts={dict(sorted(Counter(row['evidence_status'] for row in rows).items()))}")


if __name__ == "__main__":
    main()
